### ISSUE TITLE
Server returned HTTP response code: 401 for URL

### ISSUE THREAD

**Issue by Djninja926** [AndrewCPU/elevenlabs-api#5]
I get this error when i run the command `Voice.generate()` and when I click on the link that it goes to and outputs (https://api.elevenlabs.io/v1/text-to-speech/VR6AewLTigWG4xSOukaG) I get this "{"detail":"Method Not Allowed"}"

It seems like it's registering with my API because there is no connection to when I set the key in the ElevenLabsAPI object voiceAPI and when I try to generate a file with the Voice object LunaVoice.  Any help is greatly appreciated

[REMOVED FOR PRIVACY]

![Screenshot 2023-06-02 174005](https://github.com/AndrewCPU/elevenlabs-api/assets/54489434/214d2a26-83f1-4655-8983-9ed991df7e8d)

**Comment by Andrewcpu** [comment]
Hi, maybe there was an API outage or change.. I've released a new snapshot version for 2.0.. The documentation has been updated as well (mostly).

Try this dependency:
<dependency>
  <groupId>net.andrewcpu</groupId>
  <artifactId>elevenlabs-api</artifactId>
  <version>2.0-SNAPSHOT</version>
</dependency>

Be sure to reset your ElevenLabsAPI key because you included it in your screenshot.
